name: "Setup rclone"
description: "Install and configure rclone"
runs:
  using: "composite"
  steps:
    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash
        rclone version
      shell: bash

    - name: Configure rclone
      env:
        RCLONE_CONF_BASE64: ${{ secrets.RCLONE_CONF_BASE64 }}
      run: |
        mkdir -p ~/.config/rclone
        echo "$RCLONE_CONF_BASE64" | base64 -d > ~/.config/rclone/rclone.conf
        chmod 600 ~/.config/rclone/rclone.conf
      shell: bash