name: Generate Weekly Report

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-weekly-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly report script
        run: |
          python GenerateWeeklyReport.py

            - name: Commit and push generated report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add WeeklyReport/*
          git commit -m "📝 Auto-update weekly vulnerability report on $(date '+%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
