name: Generate Report

on:
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
      - '.env'
      - 'src/**'

permissions:
  contents: write

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    environment: WT_WeeklyTriggerEnv
    outputs:
      python-version: ${{ steps.setup-python.outputs.python-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Call setup-python
        id: setup-python
        uses: ./.github/workflows/PythonSetup

      - name: Set up rclone
        uses: ./.github/workflows/RcloneSetup
        with:
          rclone_conf_base64: ${{ secrets.RCLONE_CONF_BASE64 }}

      - name: DEBUG - Check rclone connection
        run: rclone lsd gdrive:/Geek/PythonPackageManager/WeeklyReports/

  generate-report:
    name: Generate Weekly Report
    runs-on: ubuntu-latest
    needs: setup
    environment: WT_WeeklyTriggerEnv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DEBUG - Check pip health
        run: |
          pip --version
          python -c "import pip._vendor.resolvelib; print(pip._vendor.resolvelib.__file__)"

      - name: DEBUG - Print config.env
        run: grep -E '^(FULL_RELOAD_PACKAGES|BASE_PACKAGE_CSV|REQUIREMENTS_FILE)=' .env || true

      - name: Run weekly report script
        run: python GenerateReport.py

  commit-changes:
    name: Commit & Push Changes
    runs-on: ubuntu-latest
    needs: generate-report
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DEBUG - Show changed files
        run: |
          git status
          git diff --name-only

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add WeeklyReport/* || true
          git commit -m "📝 Update WeeklyReport on $(date '+%Y-%m-%d %H:%M')" || echo "No changes in WeeklyReport"

          git add src/BasePackageWithDependencies.csv || true
          git commit -m "📦 Update BasePackageWithDependencies on $(date '+%Y-%m-%d %H:%M')" || echo "No changes in BasePackageWithDependencies"

          git push origin HEAD:${{ github.ref_name }}

  upload-report:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: generate-report
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to Google Drive
        run: |
          rclone copy WeeklyReport gdrive:/Geek/PythonPackageManager/WeeklyReports/ --create-empty-src-dirs --verbose --checkers=8 --stats=10s
