name: Generate Weekly Report

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  run-weekly-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Debug - Print config.env values
        run: |
          echo "FULL_RELOAD_PACKAGES=$(grep FULL_RELOAD_PACKAGES .env | cut -d '=' -f2)"
          echo "BASE_PACKAGE_CSV=$(grep BASE_PACKAGE_CSV .env | cut -d '=' -f2)"
          echo "REQUIREMENTS_FILE=$(grep REQUIREMENTS_FILE .env | cut -d '=' -f2)"

      - name: Run weekly report script
        run: python GenerateWeeklyReport.py

      - name: Commit and push generated report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add WeeklyReport/*
          git commit -m "📝 Auto-update weekly vulnerability report on $(date '+%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}

